### ISSUE TITLE
about datasets/jigsaw-unintended-bias-in-toxicity-classification/toxicity_gte0.5.txt files

### ISSUE THREAD

**Issue by minbeomkim** [alisawuffles/DExperts#4]
Hello, I'm very impressed by your research.

I want to finetune gpt2 for toxic dataset but I cannot find datasets/jigsaw-unintended-bias-in-toxicity-classification/toxicity_gte0.5.txt files in your toxic_finetune scripts

Could you share those files? or directly fine-tuned models?

Thankyou!

**Comment by alisawuffles** [comment]
Hi there,

You can find instructions for downloading the datasets and finetuned models here: https://github.com/alisawuffles/DExperts#downloading-the-original-data-and-models-from-our-paper

That should have both the dataset you're looking for as well as the corresponding finetuned anti-expert!

**Comment by minbeomkim** [comment]
Thanks a lot! I I will look forward to your wonderful research
