### ISSUE TITLE
Missing `nontoxic_prompts-10k.jsonl`

### ISSUE THREAD

**Issue by haikangdeng** [alisawuffles/DExperts#7]
Hi, I want to use the same 10k nontoxic subset that you used for evaluation, just for consistency. However, the file is missing from the repository Do you mind sharing the file again, thanks!

**Comment by luizapozzobon** [comment]
Hey @haikangdeng, I believe you can get that data with the commands below [as described in this section of the readme](https://github.com/alisawuffles/DExperts#downloading-the-original-data-and-models-from-our-paper).

```bash
gdown https://drive.google.com/uc?id=1bI49aJvmEoLdqSNb30JkORdsNJmv7Aep
unzip prompts.zip && rm prompts.zip
```

**Comment by haikangdeng** [comment]
Ah, thank you so much
